use_frameworks!

platform :ios, '8.0'

target 'JKPlayAudioKit_Example' do
  pod 'JKPlayAudioKit', :path => '../'

  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'SDWebImage', '~>3.7'
  pod 'SVProgressHUD'
  
  target 'JKPlayAudioKit_Tests' do
    inherit! :search_paths

    
  end
end
